// Package banner renders the Stack Stitcher ASCII art banner for use as the
// TUI title and CLI startup splash. The figlet text is shared across all
// three repos; only the color gradient differs, sourced from that repo's
// active appstyles.Theme.
package banner

import (
	"strings"

	"charm.land/lipgloss/v2"

	"github.com/filipemolina/cais/src/appstyles"
)

// figletLines is the pre-rendered ASCII art for "Stack Stitcher" (font: slant).
// Generated by pyfiglet; stored as Go string literals to avoid a runtime
// dependency on an external font file.
var figletLines = []string{
	"   _____ __             __      _____ __  _ __       __             ",
	"  / ___// /_____ ______/ /__   / ___// /_(_) /______/ /_  ___  _____",
	"  \\__ \\/ __/ __ `/ ___/ //_/   \\__ \\/ __/ / __/ ___/ __ \\/ _ \\/ ___/",
	" ___/ / /_/ /_/ / /__/ ,<     ___/ / /_/ / /_/ /__/ / / /  __/ /    ",
	"/____/\\__/\\__,_/\\___/_/|_|   /____/\\__/\\__/\\__/\\___/_/ /_/\\___/_/",
}

// Banner renders the figlet banner with a horizontal gradient from the
// theme's Accent color to its StatusStarting color, applied per-line
// using lipgloss truecolor. Each line gets a color interpolated along
// the gradient, creating a smooth color sweep across the text.
func Banner(t appstyles.Theme) string {
	cols := lipgloss.Blend1D(len(figletLines), t.Accent, t.StatusStarting)
	var sb strings.Builder
	for i, line := range figletLines {
		fg := cols[i]
		style := lipgloss.NewStyle().Foreground(fg)
		sb.WriteString(style.Render(line))
		if i < len(figletLines)-1 {
			sb.WriteByte('\n')
		}
	}
	return sb.String()
}
